import Link from "next/link";
import { ChevronUp } from "lucide-react";
import type { OwnershipNode } from "@/lib/ownership-graph";
import { COMPANY_TYPE_LABELS } from "@/lib/constants";
import { CitationMarker } from "@/components/citation";

type Props = {
  chain: OwnershipNode[];
  /** Map from edge id → citation numbers, generated by parent page from CitationRegistry. */
  edgeCitations?: Record<string, number[]>;
};

export function OwnershipChain({ chain, edgeCitations = {} }: Props) {
  if (chain.length === 0) return null;
  // Render bottom-up: yard at the bottom, ultimate owner at the top, like a stacked card.
  const reversed = [...chain].reverse();
  return (
    <ol className="space-y-2" aria-label="Ownership chain">
      {reversed.map((node, idx) => {
        const isTop = idx === 0;
        const isBottom = idx === reversed.length - 1;
        const linkBase = node.company.type === "yard" ? "/yard" : node.company.type === "pe_firm" || node.company.type === "public_company" || node.company.type === "family_office" ? "/owner" : "/company";
        return (
          <li key={node.company.id} className="relative">
            <div className="rounded-md border border-[var(--color-rule)] bg-[var(--color-paper)] p-4 flex items-baseline justify-between gap-4">
              <div>
                <div className="text-xs uppercase tracking-wide text-[var(--color-muted)]">
                  {isTop ? "Ultimate owner" : isBottom ? "On the sign" : `Owned by`}
                </div>
                <div className="mt-1">
                  <Link
                    href={`${linkBase}/${node.company.slug}`}
                    className="font-serif text-lg hover:underline"
                  >
                    {node.company.name}
                  </Link>
                  {node.edge && edgeCitations[node.edge.id] ? (
                    <CitationMarker numbers={edgeCitations[node.edge.id]} />
                  ) : null}
                </div>
                <div className="mt-0.5 text-xs text-[var(--color-muted)]">
                  {COMPANY_TYPE_LABELS[node.company.type]}
                  {node.company.ticker ? ` · ${node.company.ticker}` : ""}
                  {node.edge?.stakePct ? ` · ${node.edge.stakePct}% stake` : ""}
                  {node.edge?.startDate ? ` · since ${node.edge.startDate}` : ""}
                </div>
              </div>
            </div>
            {!isBottom ? (
              <div className="flex justify-center py-1 text-[var(--color-muted)]" aria-hidden>
                <ChevronUp className="size-4" />
              </div>
            ) : null}
          </li>
        );
      })}
    </ol>
  );
}
